--- 
databaseChangeLog:
   - changeSet:
      id: 1
      author: pradyutsarma
      changes:
        - createTable:
            tableName: service_instance
            columns:
              - column:
                  name: service_id
                  type: varchar(40)
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: org_id
                  type: varchar(40)
                  constraints:
                    nullable: false
              - column:
                  name: space_id
                  type: varchar(40)
                  constraints:
                    nullable: false