---
name: Check Java Formatting

on:
  pull_request:

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      
      - name: Checkstyle
        run: |
          pushd scheduler
            mvn --no-transfer-progress jxr:jxr
            mvn --no-transfer-progress checkstyle:checkstyle
            ls -alh target/checkstyle*
          popd

          #      - uses: axel-op/googlejavaformat-action@v3
          #        with:
          #          skipCommit: true
          #          args: "--skip-sorting-imports --set-exit-if-changed"
