---
name: Check Java Formatting

on:
  pull_request:

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
  
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Checkstyle
        run: |
          pushd scheduler
            mvn --no-transfer-progress jxr:jxr
            mvn --no-transfer-progress checkstyle:checkstyle
          popd

      - name: Publish Results
        run: |
         go run format_checkstyle.go
          
