---
name: Check Java Formatting

on:
  pull_request:

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master

          #      - uses: axel-op/googlejavaformat-action@v3
          #        with:
          #          skipCommit: true
          #          args: "--skip-sorting-imports --set-exit-if-changed"
